### ISSUE TITLE
Exposing Client secret and key

### ISSUE THREAD

**Issue by CeoFred** [alexandrtovmach/react-twitter-login#10]
Using the twitter client secret and key on the frontend , is that not a security risk?

**Comment by adiprerepa** [comment]
was a bit thrown off by this. its a HUGE security risk, and it shouldn't take much work to add `config.js` to the `.gitignore`.

**Comment by alexandrtovmach** [comment]
Actually @CeoFred right, and keeping secrets on client side it's not secure thing. Check [this thread](https://twittercommunity.com/t/authentication-in-client-side-app/71523) for more detailed answer.
@adiprerepa Doesn't matter do you hardcoded it, or placed to config.js, in both cases secret will be visible in final build. This package was created initially for development purposes, not for production, that's why I forgot to add this note to README

**Comment by alexandrtovmach** [comment]
@CeoFred thanks for reporting this issue :+1:, added notes in #18
