### ISSUE TITLE
Callback URL "xxxx" is not confirmed. Please check that is whitelisted within the Twitter app settings.

### ISSUE THREAD

**Issue by kaysinho** [alexandrtovmach/react-twitter-login#24]
I'm trying to use this library but the request-token get this error. 

Callback URL "https://kaysinho.github.io/TwitterApp-React/" is not confirmed. Please check that is whitelisted within the Twitter app settings.

Your App demo doesn't work, it's getting the same error.

In my TwitterApp i have this configuration:
Callback URL
https://kaysinho.github.io/TwitterApp-React/

Thank you.

**Comment by quyenhair2109** [comment]
I have exactly the same problem with this component

**Comment by exroot** [comment]
Same problem here

**Comment by Vishal1419** [comment]
Still facing the same issue. Anyone has got any ideas to solve it?

**Comment by alexandrtovmach** [comment]
Thanks everyone for paying attention here!
Investigated a bit, and found that https://cors-anywhere.herokuapp.com/corsdemo not providing unlimited access anymore. That's why this package not works anymore :man_shrugging: 

Will take a look [for alternative](https://blog.bridged.xyz/cors-anywhere-for-everyone-free-reliable-cors-proxy-service-73507192714e)

**Comment by alexandrtovmach** [comment]
Fixed in v1.4.0
